name: Deploy To Environment
description: Deploys to a specified environment

inputs:
  validateOnly:
    description: "Run the deployment as validation only"
    type: boolean
  environmentName:
    description: "The name of the environment you are deploying to"
    type: string
    required: true
  sfdx_auth_url:
    description: "The auth url tied to your deployment environment"
    required: true
  testlevel:
    description: "Test type to Run Test class"
  
  

runs:
  using: "composite"

  
  
  steps:      
    - name: Deploy to ${{ inputs.environmentName }}
      shell: bash
      env:
        SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
      run: |
        deployFlags=(
            --manifest "${SFDX_Package_Gen}"
            --wait 30
            --test-level  ${{github.event.inputs.testlevel}}
            --ignore-conflicts
            --verbose
          )
        if [ "${{ inputs.validateOnly }}" = "true" ]; then
          deployFlags+=( --dry-run )
        fi
        sfdx project deploy start "${deployFlags[@]}"