public with sharing class CCClass {
    public CCClass() {

        System.debug('Updated Changes from UI git hub');
    }

    public void getAllCases(){
        list<account> acc=[select id,name from account limit 1];
        System.debug('In VFS CC Class');
        System.debug('Updated Changes from UI');
        System.debug('Updated Changes from UI');
        System.debug('Updated Changes from UI');
        System.debug('Updated Changes from UI');
        System.debug('Updated Changes from UI12');
        System.debug('Updated Changes from UI12');
        System.debug('class name');
        System.debug('class name1');
        System.debug('class name');
        System.debug('class name');

    }
}