name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      Feature_Branch:
        type: String
        Description: Please Enter Branch name
      environment:
        type: choice
        description: Which environment to deploy to
        options:
          - Intdev
          - production
        default: "Intdev"
        required: true
      testlevel:
        type: choice
        description: "Select Test class Run Type "
        options:
          - NoTestRun
          - RunLocalTests
          - RunSpecifiedTests
          - RunAllTestsInOrg
      validateOnly:
        description: "Run the deployment as validation only"
        type: boolean
        default: false


jobs:
  deploy-partial-sandbox:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'Intdev' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3 
        with:
          fetch-depth: 0
      - name: Get Workspace
        run: |
            echo "${{ github.workspace }}"
            echo $GITHUB_WORKSPACE
      - name: Install SFDX
        run: |
          npm install --global sfdx-cli
          sfdx --version
      - name: Login To Org
        run: |
          sfdx org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL_INTDEV }}")

      - name: Run Test Classes
        run: |
          if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests' }};
              testclass =${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
              sfdx force:source:deploy --checkonly -w 500 -x ${testclass} --targetusername ${{ secrets.SFDX_AUTH_URL_INTDEV }} -l ${{github.event.inputs.testlevel}} --wait 500
          elif: ${{ github.event.inputs.testlevel == 'NoTestRun' }};
              sfdx force:source:deploy --checkonly -w 500 -x ${testclass} --targetusername ${{ secrets.SFDX_AUTH_URL_INTDEV }} -l NoTestRun--wait 500
               
          else :
              sfdx apex run test -l ${{github.event.inputs.testlevel}} -w 15
          fi
      - name: Deploy to intdev
        uses: ./.github/actions/deploy-environment
        with:
          sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL_INTDEV }}
          environmentName: ${{ github.event.inputs.environment }}
          validateOnly: ${{ github.event.inputs.validateOnly }}

  deploy-prod:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'production' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Workspace
        run: |
          echo "${{ github.workspace }}"
          echo $GITHUB_WORKSPACE
      - name: Install SFDX
        run: |
          npm install --global sfdx-cli
          sfdx --version
      - name: Login To Org
        run: |
          sfdx org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL_PRODUCTION }}")
      - name: Extract branch name
        run: |
          echo " ${{ github.head_ref || github.ref_name }} "
      - name: Run Test Classes
        run: |
          if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests' }}; then
              testclass =${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
              sfdx force:source:deploy --checkonly -w 500 -x ${testclass} --targetusername ${{ secrets.SFDX_AUTH_URL_INTDEV }} -l ${{github.event.inputs.testlevel}} --wait 500
          elif: ${{ github.event.inputs.testlevel == 'NoTestRun' }}; then
              sfdx force:source:deploy --checkonly -w 500 -x ${testclass} --targetusername ${{ secrets.SFDX_AUTH_URL_INTDEV }} -l NoTestRun--wait 500
                
          else :
              sfdx apex run test -l ${{github.event.inputs.testlevel}} -w 15
          fi

      - name: Deploy to production
        uses: ./.github/actions/deploy-environment
        with:
          sfdx_auth_url: ${{ secrets.SFDX_AUTH_URL_PRODUCTION }}
          environmentName: ${{ github.event.inputs.environment }}
          validateOnly: ${{ github.event.inputs.validateOnly }}