name: Validation Pipeline

on:
  workflow_dispatch:
    inputs:
      Feature_Branch:
        type: String
        Description: Please Enter Branch name
        required: true
      environment:
        type: choice
        description: Which environment to deploy to
        options:
          - Intdev
          - Production
        default: "Intdev"
        required: true
      testlevel:
        type: choice
        description: "Select Test class Run Type "
        options:
          - NoTestRun
          - RunLocalTests
          - RunSpecifiedTests
          - RunAllTestsInOrg
        default: "RunSpecifiedTests"
        required: true

jobs:
  Validation_To_Intdev:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'Intdev' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3 
        with:
          fetch-depth: 0
      - name: Get Workspace
        run: |
            echo "${{ github.workspace }}"
            echo $GITHUB_WORKSPACE
      - name: Install SFDX
        run: |
          npm install --global sfdx-cli
          sfdx --version
      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key

      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --clientid=${{secrets.SALESFORCE_CONSUMER_KEY_INTDEV }} --jwtkeyfile=server.key --username=${{ secrets.SFDX_AUTH_INTDEV_USERNAME }} --setdefaultdevhubusername
          
      - name: Run Test Classes
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
        run: |
          value = $(cat SFDX_testclass_Gen)
          echo "ApexSpecific = $value" >> $GITHUB_ENV
          if [ "${{ github.event.inputs.testlevel}}" == "RunSpecifiedTests"]; then
            sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_INTDEV_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} -r ${{env.ApexSpecific}}

          elif [ "${{ github.event.inputs.testlevel}}" == "NoTestRun"]; then
            sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_INTDEV_USERNAME }} -l ${{github.event.inputs.testlevel}} --wait 500    
          else
            sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_INTDEV_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --wait 500
          fi

  Validation_To_prodction:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'Production' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX
        run: |
          npm install --global sfdx-cli
          sfdx --version
      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --clientid=${{secrets.SALESFORCE_CONSUMER_KEY_PRODUCTION }} --jwtkeyfile=server.key --username=${{ secrets.SFDX_AUTH_PRODUCTION_USERNAME }} --setdefaultdevhubusername
      - name: Fetch Test class names
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
        run: |             
            cat ${SFDX_testclass_Gen} < (echo test)
      - name: validation to ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
        run: |
          
          if [ "${{ github.event.inputs.testlevel}}" == "RunSpecifiedTests"]; then
            sfdx force:source:deploy -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_PRODUCTION_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${test} 
            
          elif [ "${{ github.event.inputs.testlevel}}" == "NoTestRun"]; then
            sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_PRODUCTION_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --wait 500    
          else
            sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_PRODUCTION_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --wait 500
          fi
