name: VFS Deployment Pipeline
on:
  workflow_dispatch:
    branches:
      - Dev
    inputs:
      Feature_Branch:
        type: String
        description: Please Enter Branch To Deploy in Environment. 
        required: true
      environment:
        type: choice
        description: Please Select The Deployment Environment.
        options:
          - VFS QA
          - VFS QAGlobal
          - VFS UAT
          - VFS HOTFIX
        default: "VFS QA"
        required: true
      testlevel:
        type: choice
        description: "Select Test class Run Type"
        options:
          - NoTestRun
          - RunLocalTests
          - RunSpecifiedTests
          - RunAllTestsInOrg
        default: "RunSpecifiedTests"
        required: true
      specifiedclass:
        type: String
        description: Please Enter Test Class Names with Comma Seperated.

jobs:
  Deployment_To_VFS_QA:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'VFS QA' && github.ref == 'refs/head/Dev' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX
        run: |
          npm install -g @salesforce/cli@latest
          sfdx --version
      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY_VFS_QA }} --jwt-key-file=server.key --username=${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} --set-default-dev-hub
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html --verbose
          results-artifact-name: salesforce-code-analyzer-results
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.exit-code }}"
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
      - name: validation with RunLocalTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}
        
      - name: validation with RunAllTestsInOrg for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 

      - name: validation with NoTestRun for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} 

      - name: validation with RunSpecifiedTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${SFDX_testclass}

      - name: Deploy to ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
        run: |
          sfdx force:source:deploy  -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }}

  Deployment_To_VFS_QAGlobal:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'VFS QAGlobal' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX
        run: |
          npm install -g @salesforce/cli@latest
          sfdx --version
      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY_VFS_QAGLOBAL }} --jwt-key-file=server.key --username=${{ secrets.SFDX_AUTH_VFS_QAGLOBAL_USERNAME }} --set-default-dev-hub
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html --verbose
          results-artifact-name: salesforce-code-analyzer-results
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.exit-code }}"
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
      - name: validation with RunLocalTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_VFS_QAGLOBAL_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}
        
      - name: validation with RunAllTestsInOrg for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QAGLOBAL_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 

      - name: validation with NoTestRun for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QAGLOBAL_USERNAME }} 

      - name: validation with RunSpecifiedTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QAGLOBAL_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${SFDX_testclass}

      - name: Deploy to ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
        run: |
          sfdx force:source:deploy  -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QAGLOBAL_USERNAME }}

  Deployment_To_VFS_UAT:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'VFS UAT' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX
        run: |
          npm install -g @salesforce/cli@latest
          sfdx --version
      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY_VFS_UAT }} --jwt-key-file=server.key --username=${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} --set-default-dev-hub
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html --verbose
          results-artifact-name: salesforce-code-analyzer-results
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.exit-code }}"
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
      - name: validation with RunLocalTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}

      - name: validation with RunAllTestsInOrg for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 


      - name: validation with NoTestRun for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} 

      - name: validation with RunSpecifiedTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${SFDX_testclass}
      - name: Deploy to ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
        run: |
          sfdx force:source:deploy  -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }}
  Deployment_To_VFS_HOTFIX:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'VFS HOTFIX' }}
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli@latest
          sfdx --version
      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY_VFS_HOTFIX}} --jwt-key-file=server.key --username=${{ secrets.SFDX_AUTH_VFS_HOTFIX_USERNAME }} --set-default-dev-hub
      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target . --outfile results.html --verbose
          results-artifact-name: salesforce-code-analyzer-results
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.exit-code }}"
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
      - name: validation with RunLocalTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_VFS_HOTFIX_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}
        
      - name: validation with RunAllTestsInOrg for ${{ github.event.inputs.environment }} 
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_HOTFIX_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 

      - name: validation with NoTestRun for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_HOTFIX_USERNAME }} 

      - name: validation with RunSpecifiedTests for ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_HOTFIX_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${SFDX_testclass}

      - name: Deploy to ${{ github.event.inputs.environment }}
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
        run: |
          sfdx force:source:deploy  -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_HOTFIX_USERNAME }}

