name: VFS Validation Pipeline 
on:
  workflow_dispatch:
    inputs:
      Feature_Branch:
        type: String
        description: Please Enter Branch To validate in Environment. 
        required: true
      environment:
        type: choice
        description: Please Select The Validation Environment.
        options:
          - VFS QA
          - VFS UAT
        default: "VFS QA"
        required: true
      testlevel:
        type: choice
        description: Select Test class Run Type.
        options:
          - NoTestRun
          - RunLocalTests
          - RunSpecifiedTests
          - RunAllTestsInOrg
        default: "RunSpecifiedTests"
        required: true
      specifiedclass:
        type: String
        description: Please Enter Test Class Names with Camma Seperated.

jobs:
  Validation_To_VFS_QA:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'VFS QA' }}
    steps:
      - name: Check out files
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli@latest
          sfdx --version
      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install @salesforce/sfdx-scanner@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v1
        with:
          run-command: run
          run-arguments: --normalize-severity --target "./src,./__tests__" --outfile results.html --verbose
          results-artifact-name: salesforce-code-analyzer-results
      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.exit-code }}"
      - name: Check the outputs to determine whether to fail
        if: |
          steps.run-code-analyzer.outputs.exit-code > 0 ||
          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
          steps.run-code-analyzer.outputs.num-violations > 10
        run: exit 1
      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY_VFS_QA }} --jwt-key-file=server.key --username=${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} --set-default-dev-hub

      - name: validation to ${{ github.event.inputs.environment }} with Respect to RunLocalTests
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}

      - name: validation to ${{ github.event.inputs.environment }} with Respect to RunAllTestsInOrg
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 

      - name: validation to ${{ github.event.inputs.environment }} with Respect to NoTestRun
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} 

      - name: validation to ${{ github.event.inputs.environment }} with Respect to RunSpecifiedTests
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_QA_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${SFDX_testclass}

  Validation_To_VFS_UAT:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.environment == 'VFS UAT' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install SFDX
        run: |
          npm install --global sfdx-cli
          sfdx --version
      - name: Generate JWT Key for ${{ github.event.inputs.environment }}
        shell: bash
        run: |
          echo "${{ secrets.SALESFORCE_JWT_SECRET_KEY }}" > server.key
  
      - name: Authorize To ${{ github.event.inputs.environment }}
        run: |
          sfdx force:auth:jwt:grant --client-id=${{secrets.SALESFORCE_CONSUMER_KEY_VFS_UAT }} --jwt-key-file=server.key --username=${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} --set-default-dev-hub

      - name: Run Salesforce Code Analyzer
        run: |
          sfdx force:source:lint --files force-app/main/default/* --format json > analysis_results.json
      - name: Store Analysis Results
        run: |
          mkdir -p analysis_results
          mv analysis_results.json analysis_results/analysis_results.json
          echo "::set-output name=analysis_file_path::analysis_results/analysis_results.json"

      - name: Commit Analysis Results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Salesforce code analysis results"
          file_pattern: "analysis_results/analysis_results.json"
          branch: ${{ github.ref }}

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: validation to ${{ github.event.inputs.environment }} with Respect to RunLocalTests
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunLocalTests'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen}  --targetusername  ${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} --testlevel ${{github.event.inputs.testlevel}}

      - name: validation to ${{ github.event.inputs.environment }} with Respect to RunAllTestsInOrg
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunAllTestsInOrg'}}
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} 


      - name: validation to ${{ github.event.inputs.environment }} with Respect to NoTestRun
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'NoTestRun'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} 

      - name: validation to ${{ github.event.inputs.environment }} with Respect to RunSpecifiedTests
        shell: bash
        env:
          SFDX_testclass_Gen: ${{github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_testclass.txt
          SFDX_Package_Gen: ${{ github.workspace }}/manifest/${{github.event.inputs.Feature_Branch}}_package.xml
          SFDX_testclass: ${{github.event.inputs.specifiedclass}}
        if: ${{ github.event.inputs.testlevel == 'RunSpecifiedTests'}}  
        run: sfdx force:source:deploy --checkonly -w 500 -x ${SFDX_Package_Gen} --targetusername ${{ secrets.SFDX_AUTH_VFS_UAT_USERNAME }} --testlevel ${{github.event.inputs.testlevel}} --runtests ${SFDX_testclass}